import factories.AnimalFactory
import models.AnimalDomestico

fun main (){
    var miPerro = AnimalFactory.getInstance().getRandomPerro()
    var miGato= AnimalFactory.getInstance().getRandomGato()
    println("                El mundo animal")
    println("")
    println("Lista de requerimientos:")
    println("Los perros y los gatos tienen que tener los 2 nombre,raza,peso y color:")
    println(miPerro.toString())
    println(miGato.toString())
    println("")
    println("Tienen que tener en comun los metodos Vacunar, comer y dormir")
    println(miPerro.vacunar())
    println(miGato.vacunar())
    println("")
    println(miPerro.comer())
    println(miGato.comer())
    println("")
    println(miPerro.dormir())
    println(miGato.dormir())
    println("")
    println("Tienen un metodos sobreEscritos que es HacerRuido y HacerCaso")
    println(miPerro.hacerRuido())
    println(miGato.hacerRuido())
    println("")
    var meEscuchas:Boolean =miPerro.hacerCaso()
    println("Me estas escuchando? $meEscuchas")
    meEscuchas=miGato.hacerCaso()
    println("Me estas escuchando? $meEscuchas")
    println("")
    println("Tienen metodos propios. Salir de paseo y toser bolas de pelo")
    println(miPerro.salirPaseo())
    println(miGato.toserBolaPelo())
}